### ISSUE TITLE
Question: Why use two apps?

### ISSUE THREAD

**Issue by epernst** [kine/MSDyn365BC_AppTemplate#1]
Hi Kamil,
I'm trying out your little tool here. So far promising. But why do you have the test codeunits in a separate extension? 
In my mind, then its just get more complicated and takes more time, if you have it in a dependent extension. In a large extension, then maybe, but generally I would not like to use a separate extension.
There is no requirement from MS in regards to having it separate for AppSource either?

**Comment by kine** [comment]
Hi Erik, if I am right, it is AppSource requirement to have tests in separate app...

________________________________

**Comment by epernst** [comment]
I stand corrected. Just been reading up on it (on Yammer)... Seems also to be the better way, after reading all the arguments. Especially as your main app will running, it will not have access to the test toolkit objects.
