### ISSUE TITLE
##[error]New-PSSession : Unable to load DLL 'vmcompute.dll': The specified module could not be found. (Exception from HRESULT:  0x8007007E)

### ISSUE THREAD

**Issue by andreasblueher** [kine/MSDyn365BC_AppTemplate#3]
Hello Kamil,

we ran into the next problem during "Prepare environment". Could you give us some more informationen on how you did setup the VM for the agent? We only edited the suggested settings within the repository.

Please see the attached log file if you're looking for some more information.

[logs_2649.zip](https://github.com/kine/MSDyn365BC_AppTemplate/files/2599961/logs_2649.zip)

Do you have any idea/suggestions on where to look for answers? Looking for the message we found [this issue](https://github.com/Microsoft/AL/issues/2715) and [this issue](https://github.com/docker/for-win/issues/2020). Both suggested to reinstall docker and hyper-v, but this did not solve our issue.

Thank you very much

**Comment by kine** [comment]
The VM is Windows 2016 +docker installed. Have you followed the steps from here; https://docs.docker.com/install/windows/docker-ee/ ?

**Comment by twityde** [comment]
Did you run the correct version of the build agent?
You need to run the x64 version.

**Comment by kine** [comment]
I assume that running x64 version of the agent helped. Because no communication for longer period. I am closing this (even this issue is not related to the template).
